// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCollegeEvents.Data;

#nullable disable

namespace MyCollegeEvents.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728222721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyCollegeEvents.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            CreatedBy = "د. فاطمة أحمد",
                            CreatedDate = new DateTime(2025, 7, 29, 1, 27, 21, 372, DateTimeKind.Local).AddTicks(9903),
                            Date = new DateTime(2025, 8, 28, 1, 27, 21, 372, DateTimeKind.Local).AddTicks(9357),
                            Description = "ورشة تعليمية لتعلم أساسيات البرمجة باستخدام C#",
                            Title = "ورشة البرمجة للمبتدئات"
                        },
                        new
                        {
                            EventID = 2,
                            CreatedBy = "د. سارة محمد",
                            CreatedDate = new DateTime(2025, 7, 29, 1, 27, 21, 373, DateTimeKind.Local).AddTicks(130),
                            Date = new DateTime(2025, 9, 12, 1, 27, 21, 373, DateTimeKind.Local).AddTicks(125),
                            Description = "محاضرة حول تطبيقات الذكاء الاصطناعي في الحياة العملية",
                            Title = "محاضرة الذكاء الاصطناعي"
                        },
                        new
                        {
                            EventID = 3,
                            CreatedBy = "د. نورا علي",
                            CreatedDate = new DateTime(2025, 7, 29, 1, 27, 21, 373, DateTimeKind.Local).AddTicks(132),
                            Date = new DateTime(2025, 9, 27, 1, 27, 21, 373, DateTimeKind.Local).AddTicks(131),
                            Description = "مؤتمر يهدف لتمكين المرأة في مجال التكنولوجيا",
                            Title = "مؤتمر التكنولوجيا النسائي"
                        });
                });

            modelBuilder.Entity("MyCollegeEvents.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantID"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendedBefore")
                        .HasColumnType("bit");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniversityID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("WantCertificate")
                        .HasColumnType("bit");

                    b.HasKey("ParticipantID");

                    b.HasIndex("EventID");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("MyCollegeEvents.Models.Participant", b =>
                {
                    b.HasOne("MyCollegeEvents.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MyCollegeEvents.Models.Event", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
